# i3blocks config file

command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

[memory]
label=MEM
separator=false
interval=30

[memory]
label=SWAP
instance=swap
separator=false
interval=30

[disk]
label=HOME
#instance=/mnt/data
interval=30

[openvpn]
interval=1

[iface]
#instance=wlan0
color=#00FF00
interval=10
separator=false

[wifi]
#instance=wlp3s0
interval=10
separator=false

[bandwidth]
#instance=eth0
interval=5

[cpu_usage]
label=CPU
interval=10
min_width=CPU: 100.00%
#separator=false

[batteryBlock]
label=⚡
interval=1
command=bash ~/.config/i3/scripts/batteryBlock.sh

[volume]
instance=Master
label=
interval=1
signal=10
command=/usr/share/i3blocks/volume 5 pulse

[time]
command=date '+%d %b %Y %H:%M:%S'
label=
interval=1

[keyindicator]
instance=CAPS
interval=once
label=
signal=11
